###
GET http://localhost:9200

### p.17
PUT http://localhost:9200/_snapshot/javacafe
Content-Type: application/json

{
  "type": "fs",
  "settings": {
    "location": "/REPO/search_example",
    "compress": true
  }
}

### p.18
GET http://127.0.0.1:9200/_snapshot/javacafe/_all

### 스냅샷 복구
POST http://localhost:9200/_snapshot/javacafe/movie-search/_restore

### 복구한 스냡샷 확인
GET http://localhost:9200/_cat/indices/movie_search?v


### p.18
PUT http://localhost:9200/_snapshot/apache-web-log
Content-Type: application/json

{
  "type": "fs",
  "settings": {
    "location": "/REPO/agg_example",
    "compress": true
  }
}

### p.19
GET http://127.0.0.1:9200/_snapshot/apache-web-log/_all

### 2개의 스냡샷 중 `default` 스냅샷 복구
POST http://localhost:9200/_snapshot/apache-web-log/default/_restore

### 복구한 스냡샷 확인
GET http://localhost:9200/_cat/indices/apache*?v

### 나머지 `applied-mapping` 스냅샷 복구
POST http://localhost:9200/_snapshot/apache-web-log/applied-mapping/_restore

### 복구한 스냡샷 확인
GET http://localhost:9200/_cat/indices/apache*?v

###
