### 은전한잎 형태소 분석기 등록
PUT http://localhost:9200/seunjeon_default_analyzer
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 5,
    "number_of_replicas": 1,
    "index": {
      "analysis": {
        "analyzer": {
          "korean": {
            "type": "custom",
            "tokenizer": "seunjeon_default_tokenizer"
          }
        },
        "tokenizer": {
          "seunjeon_default_tokenizer": {
            "type": "seunjeon_tokenizer",
            "index_eojeol": false,
            "user_words": [
              "낄끼+빠빠,-100", "c\\+\\+", "어그로", "버카충", "abc마트"
            ]
          }
        }
      }
    }
  }
}

### 은전한닢 사용자 사전 추가
# 값이 작을 수록 가중치가 높음
PUT localhost:9200/seunjeon_with_dic_analyzer
Content-Type: application/json

{
  "settings": {
    "index": {
      "analysis": {
        "tokenizer": {
          "seunjeon_default_tokenizer": {
            "index_eojeol": "false",
            "pos_tagging": "false",
            "user_dict_path": "dic/seunjeon_user_dic.csv",
            "type": "seunjeon_tokenizer"
          }
        },
        "analyzer": {
          "korean": {
            "filter": [
              "lowercase"
            ],
            "tokenizer": "seunjeon_default_tokenizer",
            "type": "custom"
          }
        }
      }
    }
  }
}

###
# TODO : 검색 방법
POST localhost:9200/seunjeon_with_dic_analyzer/_analyze
Content-Type: application/json

{
  "analyzer": "korean",
  "text": "삼전 삼성전자 분식회계"
}

###
