# 7.3.3.2 확장된 Ngram 검색 적용하기
### 인덱스 생성
PUT http://localhost:9200/ac_test2
Content-Type: application/json

{
    "settings" : {
        "index" : {
            "number_of_shards" : 5,
            "number_of_replicas" : 1
        },
		"analysis": {
			"analyzer": {
				"ngram_analyzer" : {
					"type" : "custom",
					"tokenizer" : "ngram_tokenizer",
					"filter" : [
						"lowercase",
						"trim"
					]
				},
				"edge_ngram_analyzer" : {
					"type" : "custom",
					"tokenizer" : "edge_ngram_tokenizer",
					"filter" : [
						"lowercase",
						"trim",
						"edge_ngram_filter_front"
					]
				},
				"edge_ngram_analyzer_back" : {
					"type" : "custom",
					"tokenizer" : "edge_ngram_tokenizer",
					"filter" : [
						"lowercase",
						"trim",
						"edge_ngram_filter_back"
					]
				}
			},
			"tokenizer" : {
				"ngram_tokenizer" : {
					"type" : "nGram",
					"min_gram" : "1",
					"max_gram" : "50",
					"token_chars" : [
						"letter",
						"digit",
						"punctuation",
						"symbol"
					]
				},
				"edge_ngram_tokenizer" : {
					"type" : "edgeNGram",
					"min_gram" : "1",
					"max_gram" : "50",
					"token_chars" : [
						"letter",
						"digit",
						"punctuation",
						"symbol"
					]
				}
			},
			"filter": {
				"edge_ngram_filter_front" : {
					"type" : "edgeNGram",
					"min_gram" : "1",
					"max_gram" : "50",
					"side" : "front"
				},
				"edge_ngram_filter_back" : {
					"type" : "edgeNGram",
					"min_gram" : "1",
					"max_gram" : "50",
					"side" : "back"
				}
			}
		}
	}
}

### 매핑 생성
PUT http://localhost:9200/ac_test2/_mapping/ac_test2
Content-Type: application/json

{
	"properties": {
		"item": {
			"type": "keyword",
			"boost": 30
		},
		"itemNgram": {
			"type": "text",
			"analyzer": "ngram_analyzer",
			"search_analyzer": "ngram_analyzer",
			"boost": 3
		},
		"itemNgramEdge": {
			"type": "text",
			"analyzer": "edge_ngram_analyzer",
			"search_analyzer": "ngram_analyzer",
			"boost": 2
		},
		"itemNgramEdgeBack": {
			"type": "text",
			"analyzer": "edge_ngram_analyzer_back",
			"search_analyzer": "ngram_analyzer",
			"boost": 1
		}
	}
}

### Bulk Insert
POST http://localhost:9200/ac_test2/_bulk
Content-Type: application/json

{"index" : { "_index" : "ac_test2", "_type" : "ac_test2", "_id" : "1" }}
{"item" : "신혼", "itemNgram" : "신혼", "itemNgramEdge" : "신혼", "itemNgramEdgeBack" : "신혼"}
{"index" : { "_index" : "ac_test2", "_type" : "ac_test2", "_id" : "2" }}
{"item" : "신혼가전", "itemNgram" : "신혼가전", "itemNgramEdge" : "신혼가전", "itemNgramEdgeBack" : "신혼가전"}
{"index" : { "_index" : "ac_test2", "_type" : "ac_test2", "_id" : "3" }}
{"item" : "신혼가전특별전", "itemNgram" : "신혼가전특별전", "itemNgramEdge" : "신혼가전특별전", "itemNgramEdgeBack" : "신혼가전특별전"}

### 검색
# 검색어와 정확하게 일치하는 문서가 밑에 옴
POST http://localhost:9200/ac_test2/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "prefix": {
            "item": "신혼"
          }
        },
        {
          "term": {
            "itemNgram": "신혼"
          }
        },
        {
          "term": {
            "itemNgramEdge": "신혼"
          }
        },
        {
          "term": {
            "itemNgramEdgeBack": "신혼"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}

### `keyword` item 추가하여 검색어 일치 우선
POST http://localhost:9200/ac_test2/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "prefix": {
            "item": "신혼"
          }
        },
        {
          "term": {
            "item": "신혼"
          }
        },
        {
          "term": {
            "itemNgram": "신혼"
          }
        },
        {
          "term": {
            "itemNgramEdge": "신혼"
          }
        },
        {
          "term": {
            "itemNgramEdgeBack": "신혼"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}

### 스코어 값 비교
# item 필드 검색 없을 경우
POST http://localhost:9200/ac_test2/_search
Content-Type: application/json

{
  "explain": true,
  "query": {
    "bool": {
      "should": [
        {
          "prefix": {
            "item": "신혼"
          }
        },
        {
          "term": {
            "itemNgram": "신혼"
          }
        },
        {
          "term": {
            "itemNgramEdge": "신혼"
          }
        },
        {
          "term": {
            "itemNgramEdgeBack": "신혼"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}

### item 필드 검색일 경우
POST http://localhost:9200/ac_test2/_search
Content-Type: application/json

{
  "explain": true,
  "query": {
    "bool": {
      "should": [
        {
          "prefix": {
            "item": "신혼"
          }
        },
        {
          "term": {
            "item": "신혼"
          }
        },
        {
          "term": {
            "itemNgram": "신혼"
          }
        },
        {
          "term": {
            "itemNgramEdge": "신혼"
          }
        },
        {
          "term": {
            "itemNgramEdgeBack": "신혼"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}

###
