### 인덱스 생성
PUT http://localhost:9200/ac_test
Content-Type: application/json

{
    "settings" : {
        "index" : {
            "number_of_shards" : 5,
            "number_of_replicas" : 1
        }
    }
}

### 매핑 설정
# 이전 방식과 다르네
PUT http://localhost:9200/ac_test/_mapping/ac_test
Content-Type: application/json

{
	"properties": {
		"itemSrc": {
			"type": "keyword"
		},
		"itemCompletion": {
			"type": "completion"
		}
	}
}

### Bulk insert
POST http://localhost:9200/ac_test/_bulk
Content-Type: application/json

{"index" : { "_index" : "ac_test", "_type" : "ac_test", "_id" : "1" }}
{"itemSrc" : "신혼", "itemCompletion" : "신혼"}
{"index" : { "_index" : "ac_test", "_type" : "ac_test", "_id" : "2" }}
{"itemSrc" : "신혼가전", "itemCompletion" : "신혼가전"}
{"index" : { "_index" : "ac_test", "_type" : "ac_test", "_id" : "3" }}
{"itemSrc" : "신혼가전특별전", "itemCompletion" : "신혼가전특별전"}

### 일반 검색
POST http://localhost:9200/ac_test/_search
Content-Type: application/json

{
    "query": {
        "match" : {
            "itemSrc" : "신혼"
        }
    }
}

### 키워드 검색
POST http://localhost:9200/ac_test/_search
Content-Type: application/json

{
	"suggest": {
		"s1": {
		  "prefix": "신혼",
		  "completion": {
			"field": "itemCompletion",
			"size" : 10
		  }
		}
	}
}

###
