version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elastic:nori
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /Users/hklee/workspace/elastic/docker/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- /Users/hklee/workspace/elastic/docker/config/analysis:/usr/share/elasticsearch/config/analysis
      - /Users/hklee/workspace/elastic/docker/config/dic:/usr/share/elasticsearch/config/dic
      - /Users/hklee/workspace/elastic/repo:/REPO
    environment:
      - "discovery.type=single-node"

  kibana:
    container_name: kibana
    image: kibana:7.0.0
    ports:
      - 5601:5601
    links:
      - elasticsearch
    #environment:
      #ELASTICSEARCH_URL: "http://localhost:9200"
