FROM elasticsearch:6.7.1

# murmur3 plugin install
#RUN bin/elasticsearch-plugin install mapper-murmur3

# 은전 한닢
RUN bin/elasticsearch-plugin install https://github.com/javacafe-project/elastic-book-etc/raw/master/plugin/elasticsearch-analysis-seunjeon-6.7.1.zip
